using System;

namespace Tests2AnotherTry2.Tests2AnotherTry2.exception
{
    internal class FileNameAlreadyExistsException : Exception{}
}
